### PR TITLE
Added okhttp and Bouncy Castle libraries back #2

### PR DESCRIPTION
**Pull request by bigfatbrowncat**
@dicej, I've added the documentation on using avian-pack to build Avian with Android classpath as you proposed, so I'm repeating the previously rejected pull request (https://github.com/ReadyTalk/avian/pull/371) with added documentation.

### CODE REVIEW

**Comment by bigfatbrowncat** [comment]
I have removed the previous Android-related part of the instruction, cause it's currently incorrect - is it ok?

**Comment by dicej** [comment]
Thanks, @bigfatbrowncat, but I'm still not clear on how to build avian-pack.  The old instructions provided a complete list of commands to run to get a working build, but the new instructions just say to "use avian-pack", which isn't very useful.

I tried this:

```
git clone https://github.com/bigfatbrowncat/avian-pack
cd avian-pack
make
```

and got this:

```
...
/bin/bash ./libtool --silent --mode=link gcc -std=gnu99 -I./lib -I. -fPIC -Wall -Wmissing-prototypes -Wstrict-prototypes -fexceptions  -DHAVE_EXPAT_CONFIG_H  -o xmlwf/xmlwf xmlwf/xmlwf.o xmlwf/xmlfile.o xmlwf/codepage.o xmlwf/unixfilemap.o libexpat.la
make[1]: Leaving directory '/home/dicej/p/avian-pack/android/external/expat'
make: *** No rule to make target 'android/external/fdlibm/makefile.in', needed by 'android/external/fdlibm/Makefile'.  Stop.
```

Maybe I missed a step somewhere, but the instructions in README.md are too vague to be helpful.

**Comment by bigfatbrowncat** [comment]
I think in your case the submodule 'expat' hasn't been pulled...
Actually, this problem wouldn't happen if you followed my guide, I think.
What's vague in it? Could you tell me the unclear moments? I checked it by asking my friend @JustAMan to read and follow them... But we work together, so some things could be more obvious for him...
Please, tell me what could I improve.

By the way, which OS are you building on?

**Comment by bigfatbrowncat** [comment]
Actually you missed the step 5 of my instruction.
You should have done 'make git-refresh'

**Comment by dicej** [comment]
Ah, my mistake.  I had assumed the instructions for building would be in avian.git's README.md, not avian-pack.git's README.md, which I hadn't noticed.  I'll try again.

I'm using Linux, BTW.

**Comment by bigfatbrowncat** [comment]
I decided to put the guide into 'avian-pack' project cause it doesn't actually depend on avian itself. Avian just supports it, but all the build procedures are made by avian-pack makefile.

**Comment by dicej** [comment]
Yup, that's fine; I was just confused.

**Comment by bigfatbrowncat** [comment]
By the way, maybe we should consider making prebuilded versions of avian with and without Android classpath? What do you think about that?

**Comment by dicej** [comment]
@sgoings has recently added support for publishing builds to oss.jfrog.org.  Perhaps you could build on that to provide Android-classpath builds as well.

**Comment by bigfatbrowncat** [comment]
Hmm... I can't open this page.
Why github releases isn't suitable for you? We could just make some builds and put links to them at avian's main page.

**Comment by dicej** [comment]
@sgoings might be able to give you a better answer, but I assume he chose jfrog.org because it is an Artifactory repository, which makes it easy to use with e.g. Gradle, Ivy, or Maven projects.  I guess we could also publish them to GitHub as well.

**Pull request merged**
