### PR TITLE
classpath-openjdk: Fix getZipFileEntry()

### PR DESCRIPTION
**Pull request by lostdj**
'addSlash' argument was incorrectly understood: it is supposed to add slash only on retry (see ZIP_GetEntry2() zip_util.c in OpenJDK).

### CODE REVIEW

**Comment by lostdj** [comment]
BUILD_STEP="PUBLISH" failed? That doesn't concern me?

**Comment by sgoings** [comment]
@lostdj - fixed that in master for you.

**Comment by joshuawarner32** [comment]
@lostdj Can you rebase this request on master to pull in @sgoings's fix, and let the travis build complete?

**Comment by lostdj** [comment]
Rebased.

**Comment by joshuawarner32** [comment]
Small stylistic note: I'd prefer `if (e == nullptr)` or maybe just `if (e)` over `if (e == 0)`.

**Comment by lostdj** [comment]
I'd prefer `if (e)`, too. But I just followed existing coding style.

**Pull request merged**
