### PR TITLE
- fixed building for iOS 9

### PR DESCRIPTION
**Pull request by benstadin**
- handle sim flag to better distinguish between ios simulator / ios
- added ios_deployment_target to set ios min version
- default to 64 bit build for iOS

### CODE REVIEW

**Comment by benstadin** [comment]
I figured I didn't remove the default copyright notices that Xcode creates for each source file. Shall I remove them?

**Comment by dicej** [comment]
Hi Ben,

Thanks for doing this and updating the hello-ios project.  I assume you meant to ask the copyright notice question on the hello-ios PR rather than this one.  Anyway, yes, we should probably remove those so they don't cause confusion.

I suppose we should really replace them with an appropriate license notice, but I never took the time to do that with the original code, so just removing them entirely is fine for now.  The intention is that it's public domain example code.

**Comment by benstadin** [comment]
Hi Joel,

I've removed the copyright notes and edited the pull request. I explicitly mention in the commit message that the code is public domain.


Von: Joel Dice <notifications@github.com<mailto:notifications@github.com>>
Antworten an: ReadyTalk/avian <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Montag, 2. November 2015 00:41
An: ReadyTalk/avian <avian@noreply.github.com<mailto:avian@noreply.github.com>>
Cc: Benjamin Stadin <benjamin.stadin@heidelberg-mobil.com<mailto:benjamin.stadin@heidelberg-mobil.com>>
Betreff: Re: [avian] - fixed building for iOS 9 (#464)


Hi Ben,

Thanks for doing this and updating the hello-ios project. I assume you meant to ask the copyright notice question on the hello-ios PR rather than this one. Anyway, yes, we should probably remove those so they don't cause confusion.

I suppose we should really replace them with an appropriate license notice, but I never took the time to do that with the original code, so just removing them entirely is fine for now. The intention is that it's public domain example code.

-

**Comment by dicej** [comment]
Thanks.  I'm updating my Xcode now so I can test this myself.

**Pull request merged**
