### PR TITLE
support AOT-compilation of Java 8 lambda expressions

### PR DESCRIPTION
**Pull request by dicej**
These expressions are tricky because they rely on invokedynamic, which
normally implies runtime code generation.  However, since lambdas
don't actually use the "dynamicness" of invokedynamic, we can convert
them into static calls to synthetic classes at compile time.

Since I had already written code to synthesize such classes in Java
and I didn't want to rewrite it in C++, I needed to add support for
running Java code to the bootimage generator.  And since the primary
VM used by the generator is purpose-built to generate AOT-compiled
code for a specific target architecture and is not capable of
generating or running JIT-compiled code for the host architecture, I
added support for loading a second, independent, host-specific VM for
running Java code.

The rest of the patch handles the fact that each method compilation
might cause new, synthetic classes to be created, so we need to make
sure those classes and their methods are included in the final heap
and code images.  This required breaking some giant code blocks out of
makeCodeImage into their own methods, which makes the diff look
scarier than it really is.

### CODE REVIEW

**Comment by dicej** [comment]
@joshuawarner32, do you have time to look at this?

**Comment by joshuawarner32** [comment]
Apologies for the delay.  The code looks fine.  Is there a way to add tests for this?

I upgraded the Dockerfiles to openjdk 8, if that helps: https://github.com/ReadyTalk/avian/pull/456.  The updated image is already pushed to docker hub as joshuawarner32/avian-build.

**Comment by dicej** [comment]
One way to test this would be to add a makefile target which builds an AOT-compiled boot image that contains all the tests in the suite and runs them each.  Currently, when you run "make bootimage=true test" the class library classes are AOT-compiled, but the test classes themselves are JIT-compiled.  I think that should still be the default, but we should have a version that AOT-compiles everything also.

I'll work on that when I get a chance; maybe next weekend or the one after that.

**Comment by joshuawarner32** [comment]
Cool.  I don't have any concerns with just merging this now, though, so...

**Pull request merged**
