### PR TITLE
add support for LZMA-enabled artifacts

### PR DESCRIPTION
**Pull request by dicej**

### CODE REVIEW

**Comment by sgoings** [comment]
I'd like to use something other than curl to grab those files... maybe: https://github.com/michel-kraemer/gradle-download-task?

**Comment by dicej** [comment]
The latest failure is a spurious failure of the Trace test, which we've seen before (and which used to go unnoticed back before #416 got fixed).  It seems to fail maybe 1% of the time.  I'll enter a new issue for that, but I'm sure it's not a regression related to this change.

**Comment by joshuawarner32** [comment]
Sorry, I didn't notice this had just been sitting around.  @sgoings - can you force-push something to this branch to trigger the build again, just for my own comfort?  This'll do it nicely: `git checkout sgoings; git commit --amend --no-edit; git push -f`.  FWIW, I spent tried to reproduce the trace failure both on my mac host, and a linux VM, to no avail (I left Joel's script in https://github.com/ReadyTalk/avian/issues/429 running for a couple hours).

**Comment by joshuawarner32** [comment]
Sorry, I didn't notice this hanging out.  My bad!

**Pull request merged**
